POST http://localhost:3001/user/register
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Three",
  "email": "userThree@gmail",
  "password": "password"
}

###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "email": "userThree@gmail",
  "password": "password"
}