POST http://localhost:3001/user/register
Content-Type: application/json

{
  "firstName": "The Fourth",
  "lastName": "User",
  "email": "numberFour@aol.com",
  "password": "notThisPasswordAgain"
}

###
POST http://localhost:3001/user/login
Content-Type: application/json

{
  "email": "numberFour@aol.com",
  "password": "notThisPasswordAgain"
}